services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_BOARD_ID=${TRELLO_BOARD_ID}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=${PORT}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    ports:
    - ${PORT}:${PORT}
    volumes:
    - ./:/home/trellobot

  webhook_generate:
    build:
      context: .
      dockerfile: webhook_generate.Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_BOARD_ID=${TRELLO_BOARD_ID}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=${PORT}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    depends_on:
    - app
    volumes:
    - ./:/home/webhook_generate
